// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FacturePorteuse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FacturePorteuse));
        
        string IMigrationMetadata.Id
        {
            get { return "202011091344021_Facture-Porteuse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
